### PR TITLE
chore: upgrade components to composition API

### PR DESCRIPTION
**Pull request by Diizzayy**
This PR upgrades the `NuxtImg` and `NuxtPicture` components to use the Composition API, and exposes a new `useImage` composable with the same behavior of the `$img` utility.

Other changes:
- the `nuxt-img` component now supports `preload`

### CODE REVIEW

**Comment by AndersNielsen85** [comment]
Would be nice adding the example directly to docs. Don't know if that should go to a separate PR? :)

```
<script lang="ts" setup>
const { generate } = useImage()
const bg = computed(() => {
  const imgUrl = generate('/images/colors.jpg', {
    width: 300,
    height: 300,
    quality: 80
  })
  return `url('${imgUrl}')`
})
</script>```

**Review by pi0 — APPROVED** [review]
Thanks for helping on this. Nice changes ❤️

**Comment by pi0** [comment]
@AndersNielsen85 I changed back usage to `$img = useImage()` (`$img` is a function with attached props)

**Comment by Diizzayy** [comment]
> Thanks for helping on this. Nice changes ❤️ 

@pi0 no problem, happy to help.

**Pull request merged**
