### PR TITLE
feat(nuxt-img): support fallback prop

### PR DESCRIPTION
**Pull request by treboryx**
issue was part of https://github.com/nuxt/image/issues/148 that I created myself, thought I'd code it myself into nuxt-image

### CODE REVIEW

**Comment by pi0** [comment]
This would be a nice feature. I'm just wondering what happens if fallback image also makes an error

**Comment by treboryx** [comment]
> This would be a nice feature. I'm just wondering what happens if fallback image also makes an error

Fallback image would be something that would always exist, like a local static file image. I don't think there's anything we can do if fallback image errors, but I can't really see why that would happen.

**Comment by pi0** [comment]
By correct usage it should be totally fine but if wrongly using a remote image which cannot be loaded (404 or network error) users might end with an infinitie loop which we should consider when adding feature

**Comment by treboryx** [comment]
> By correct usage it should be totally fine but if wrongly using a remote image which cannot be loaded (404 or network error) users might end with an infinitie loop which we should consider when adding feature

If it's a local file you don't run into the infinite loop. For remote images we can use node-fetch, which I noticed is already a dependency, and if the http status is something other than 200, return or set it to an empty image (a base64 one, similar to the GIF one you already have).


Sounds good?

**Comment by pi0** [comment]
@treboryx I think simply keeping a flag like `this._errored` is enough to set fallback twice and avoid loop

Also would be nice if you remove `package.lock.json` from PR

**Comment by treboryx** [comment]
> @treboryx I think simply keeping a flag like `this._errored` is enough to set fallback twice and avoid loop
> 
> Also would be nice if you remove `package.lock.json` from PR

Yeah that's a better idea, all done, works like a charm!

**Review by pi0 — APPROVED** [review]

**Review by Atinux — APPROVED** [review]

**Comment by Atinux** [comment]
One note, shall we also `$emit('error', event)` in `setFallbackImage` ?

**Comment by treboryx** [comment]
> One note, shall we also $emit('error', event) in setFallbackImage ?

A 404 not found error is already logged in the console, I don't think this is necessary.

**Comment by pi0** [comment]
> One note, shall we also $emit('error', event) in setFallbackImage ?

Makes sense since when fallback prop is not set, we expect identical behavior of img and nuxt-img for custom error handling, I will take care before merge :)

**Comment by treboryx** [comment]
Hi, do we know when is this going to be merged into an update? 👉👈🥺

**Comment by treboryx** [comment]
Hi again. Is there any chance you know when this is going to be merged & released with a new update?

**Comment by pi0** [comment]
Hi @treboryx. I'm SO sorry that your PR is stalled for long time. This is mostly pending because we need consistent support with `<nuxt-picture>` and also might be probably better supporting fallback in placeholder component (#189) that can properly control error handling behavior (rather than directly updating `el` reference).

**Comment by pi0** [comment]
In the meantime you can create a wrapper component. See this sandbox: https://codesandbox.io/s/trusting-euler-8h0j9?file=/components/nuxt-img-container.vue:0-482

```vue
<template>
  <nuxt-img v-bind="$attrs" @error.native="setFallbackImage" />
</template>

<script>
export default {
  props: {
    fallback: { type: String, required: false, default: undefined },
  },
  data() {
    return {
      hasError: false,
    };
  },
  methods: {
    setFallbackImage(event) {
      if (this.hasError) {
        return;
      }
      this.hasError = true;
      if (this.fallback) {
        event.target.src = this.fallback;
      }
    },
  },
};
</script>
```

**Comment by treboryx** [comment]
> In the meantime you can create a wrapper component. See this sandbox: https://codesandbox.io/s/trusting-euler-8h0j9?file=/components/nuxt-img-container.vue:0-482
> 
> ```vue
> <template>
>   <nuxt-img v-bind="$attrs" @error.native="setFallbackImage" />
> </template>
> 
> <script>
> export default {
>   props: {
>     fallback: { type: String, required: false, default: undefined },
>   },
>   data() {
>     return {
>       hasError: false,
>     };
>   },
>   methods: {
>     setFallbackImage(event) {
>       if (this.hasError) {
>         return;
>       }
>       this.hasError = true;
>       if (this.fallback) {
>         event.target.src = this.fallback;
>       }
>     },
>   },
> };
> </script>
> ```

Thanks. Looking forward to official support.

**Pull request closed without merging**
