### PR TITLE
feat: add `wagtail` provider

### PR DESCRIPTION
**Pull request by bonomite**
I created a provider to support the URL structure for the Wagtail CMS image template ([https://docs.wagtail.org/en/v4.2.1/topics/images.html](https://docs.wagtail.org/en/v4.2.1/topics/images.html))

I think I got everything set up correctly. Thanks

### CODE REVIEW

**Comment by danielroe** [comment]
Would you be able to merge the latest main and add snapshots/expected values for wagtail? 🙏

**Comment by bonomite** [comment]
@danielroe, I think we are good. Except it looks like the IPX provider test is failing
image

I'm pretty sure I had nothing to do with it. I hope.

**Review by danielroe — APPROVED** [review]

**Comment by bonomite** [comment]
Thanks! Sorry about the typo 😬

**Review by pi0 — APPROVED** [review]
Haven't locally tested but looks 💯

**Comment by pi0** [comment]
Ahh we have merge conflicts (trying to fix)

**Pull request merged**
