### PR TITLE
feat(imgix): format keys

### LINKED ISSUE #363: feat: imgix Blurhash support
https://blog.imgix.com/2021/01/26/blurhash

https://docs.imgix.com/apis/rendering/format/fm#blurhash

https://blurha.sh/

maybe data loading speed see blurhash.

### PR DESCRIPTION
**Pull request by shadow81627**
resolves #363

### CODE REVIEW

**Comment by productfrontenddeveloper** [comment]
blurhash library used ? I couldn't see https://github.com/nuxt/image/blob/main/package.json

**Comment by shadow81627** [comment]
@productfrontenddeveloper my understanding is that blurhash is a image format supported by imgix?

https://docs.imgix.com/apis/rendering/format/fm#blurhash

**Comment by productfrontenddeveloper** [comment]
imgix return blurhash -> 'e*EC|aS*ROj=WAt:f-n#WXe-N4bJtRj]j[M{oNkXj[ozRjj^a$ayfl' and see loading etc with. 

https://blog.imgix.com/2021/01/26/blurhash

https://docs.imgix.com/apis/rendering/format/fm#blurhash

https://blurha.sh/

**Comment by shadow81627** [comment]
@pi0 is it in scope for `@nuxt/image` to transform blurhash into placeholder images? https://github.com/woltapp/blurhash/tree/master/TypeScript

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
Thanks!

> is it in scope for @nuxt/image to transform blurhash into placeholder images?

Nop. It happens on server side of imgix

**Comment by productfrontenddeveloper** [comment]
> Thanks!
> 
> > is it in scope for @nuxt/image to transform blurhash into placeholder images?
> 
> Nop. It happens on server side of imgix

https://docs.imgix.com/apis/rendering/format/fm#blurhash

It only freezes a key on the imgix side, you need to use it inside. so when we add this, the picture does not come back. 

CleanShot 2021-09-06 at 07 11 10

**Comment by pi0** [comment]
You are correct @productfrontenddeveloper. We still need placeholder support (https://github.com/nuxt/image/issues/189) for loading strategy. Normally for providers not supporting blurhash, we use a pixel resized version of image but can also support native server blur ike this. 

Meanwhile this format can be useful for cases a static blurry version is desired like a banner background image.

**Pull request merged**
