### PR TITLE
feat: allow setting global `quality` defaults in config

### PR DESCRIPTION
**Pull request by Tragio**
Hi there 👋 

This PR allows setting the quality of the generated images in the module configuration.

Thank you very much for the amazing work 🚀

### CODE REVIEW

**Comment by danielroe** [comment]
You are a star - thank you ❤️

**Review by danielroe — APPROVED** [review]

**Review by hartmut-co-uk — CHANGES_REQUESTED** [review]
Great!
The solution should also apply `quality` at module config level to `<nuxt-picture>`, right?

Could you please also add tests to `test/unit/picture.test.ts`?

**Comment by Tragio** [comment]
> Great! The solution should also apply `quality` at module config level to `<nuxt-picture>`, right?
> 
> Could you please also add tests to `test/unit/picture.test.ts`?

Thank you very much 🙏  I only added one test, should I add all the tests that I did for `nuxt-img`? Just don't want to be redundant, since all is being [passed to `nuxt-picture`](https://github.com/nuxt/image/blob/main/src/runtime/components/nuxt-picture.ts#L19). If you want I can do it without any problem 🙂

**Comment by hartmut-co-uk** [comment]
Fair enough, I think this is good to go! 💪

**Review by hartmut-co-uk — APPROVED** [review]

**Pull request merged**
