### PR TITLE
Migrating module to nuxt kit (nuxt 3/bridge)

### PR DESCRIPTION
**Pull request by Rigo-m**
Hi all. Since this module has been a staple in our workflow, which we are planning to migrate to nuxt3, I wanted to take a chance at migrating it to nuxt kit to make it compatible with nuxt3.

I obviously need a hand.

For now, it seems to work just fine, but I have an error in `./playground/.nuxt/dist/server/server.mjs`, within the function `headObjToTags`. I could manually fix it by adding `obj = obj ?? {}`.

After that, it seems to work just fine and I am  confident this PR can become the stepping stone for updating the module properly.

The only gotcha I found so far, is that I can not rely on nuxt base (see `ipx.ts` TODO comment)

Migration to vitest is missing. Tests are not working for now.

@pi0 @danielroe hope I can help more 🙏

### CODE REVIEW

**Comment by Rigo-m** [comment]
Let me know if you think this is the right approach so I can continue working in it.

**Comment by Rigo-m** [comment]
`yarn build` is failing with `nuxt-module-builder`, while `yarn dev:setup` works. Trying to figure that out as well

**Comment by pi0** [comment]
Hi, @Rigo-m thanks SO MUCH for the initiative on this PR 💚 

I have a local refactor ongoing with almost the same refactors for kit support and a couple of trials for proper Nitro/IPX integration as we lacked them so far.

I'm truly sorry for the miscommunication about it (Now made #500) and have to close this PR since it would be an extra effort for me to rebase with the same changes. 

Please keep up doing your nice contributions and really looking forward to work together for best Nuxt 3 experience after basic support landed.

**Comment by Rigo-m** [comment]
Thanks @pi0, at least I'm happy I was moving in the right direction. It means I was at least grasping some concepts correctly. Is there any ETA on the new version landing? Can I help with something by any chance?

**Pull request closed without merging**
