### PR TITLE
feat: add `@error` event from `<NuxtPicture>`

### LINKED ISSUE #1251: NuxtPicture does not emit Error of child <img>
When using `<NuxtImage />` it is currently not possible to handle error cases, as the error of the child `` element is not emited.

Two changes need to be made:

1. check `data-error` attribute
2. add `imgEl.value.onerror` handler

I'll create a PR

### PR DESCRIPTION
**Pull request by dreitzner**
Closes #1251 
closes https://github.com/nuxt/image/issues/1032

Will expose the same errors that are already exposed in `<NuxtImg />` also on `<NuxtPicture />`

### CODE REVIEW

**Review by danielroe — COMMENTED** [review]
Thank you! Would you update the tests here?

https://github.com/nuxt/image/blob/df062d0333095efefe357968412c3ab24c46ad08/test/e2e/ssr.test.ts#L46-L58

**Comment by danielroe** [comment]
Did you follow the steps here? https://image.nuxt.com/get-started/contributing#how-to-contribute

**Comment by dreitzner** [comment]
> Did you follow the steps here? https://image.nuxt.com/get-started/contributing#how-to-contribute

I was searching for this link, thank you.

It might be good to add a `CONTRIBUTING.md`, that has that link, to the repo.

I'll follow the steps

**Comment by dreitzner** [comment]
@danielroe I added the picture test for ssr and no-ssr

**Review by danielroe — APPROVED** [review]

**Comment by joerees** [comment]
When is this update going to be release ?

**Pull request merged**
