### PR TITLE
feat(storyblok): update to the new service

### PR DESCRIPTION
**Pull request by jorgemartins-uon**
Updates the `storyblok` provider to use their new [Image Service API](https://www.storyblok.com/docs/image-service#migrating-from-the-previous-version-of-the-service).

Linked to #474.

### CODE REVIEW

**Review by Baroshem — APPROVED** [review]
Hey,

I think you have covered the changes pretty well!

I am giving an approval but wait for Pio with the final decision :)

**Review by Atinux — APPROVED** [review]
Checked the playground, looks good for me. Thanks @jorgemartins-uon

**Comment by sam-g-roberts** [comment]
Would be sweet if this could get merged

**Comment by venux92** [comment]
Any timeframe on when this PR will be merged?

**Comment by MacroMan** [comment]
Could this be why I'm receiving this error at runtime, or this unrelated?

```Error: Unknown provider: storyblok
    at getProvider (image.js:116:11)
    at resolveImage (image.js:82:34)
    at getImage (image.js:13:19)
    at VueComponent.$img2 (image.js:20:12)
    at VueComponent.nSrc (nuxt-img.vue:36:1)
    at Watcher.get (vue.runtime.esm.js:4495:1)
    at Watcher.evaluate (vue.runtime.esm.js:4597:1)
    at VueComponent.computedGetter [as nSrc] (vue.runtime.esm.js:4851:1)
    at Object.get (vue.runtime.esm.js:2081:1)
    at Proxy.render (nuxt-img.vue?1a92:9:10)```

**Review by pi0 — APPROVED** [review]
LGTM. Thanks for working on this <3

**Pull request merged**
